### PR TITLE
Fix Buffer Out of Bounds Error

### LINKED ISSUE #99: Buffer out of bounds when v5 connection request sent to v4 server
Caused by trying to decode a V4 connack using code expecting a V5 connack (because V5 has been set in options).

Underlying issue traced to _parseVarByteNum function in parser.js which doesn't check buffer length before reading additional UInt8.

### PR DESCRIPTION
**Pull request by bkp7**
Fix bug in _parseVarByteNum() function causing Buffer Out of Bounds Error.

Added Tests.

Also refactored the testParseGenerateDefaults() test function to separate out a new testParseOnly() which can be used directly.

Fixes #99, fixes #98, closes #78, fixes mqttjs/MQTT.js#1073, fixes mqttjs/MQTT.js#993, fixes mqttjs/MQTT.js#1176

Possible fix to mqttjs/MQTT.js#1228 which has this function in the call stack. Unfortunately no specific test provided in that issue to prove it's fixed.

Probable fix to #72, but gist and test not longer present to check it.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -515,13 +516,69 @@ testParseGenerate('no clientId with 3.1.1', {
...
+  retain: false,
+  qos: 0,
+  dup: false,
+  length: 16,
+  topic: null,
+  payload: null,
+  protocolId: 'MQTT',
+  protocolVersion: 4,
+  clean: true,
+  keepalive: 0,
```
Comment (mcollina) [inline test.js:528]: this tests had this values omitted on purpose for the generation tests, as it tests the defaults are there. It's not equivalent at the previous one.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: test.js (hunk 1 above)
Comment (bkp7) [reply test.js:540]: @mcollina, yes, sorry I looked at the test as doing both a Parse and Generate and didn't twig about the defaults (the clue was in the name!). I was after a two way test so I've created a new testParseAndGenerate to do that for my new tests.

On the existing test I have added an additional field so it takes the partial packet object, generates the mqtt bytes, and then parses those to create the fully populated packet object. I believe this now fully covers the test that was previously being done but with the added benefit of checking the generated object is exactly as expected.

**Review by mcollina — APPROVED** [review]
lgtm
